      PROGRAM SUBSP
      IMPLICIT NONE
      INTEGER, PARAMETER :: NN=3, NNM=NN+1, NWK=5, NWM=3, NC=2
      INTEGER, PARAMETER :: NNC=NC*(NC+1)/2
      INTEGER :: NROOT,NITEM,IFSS,IFPR,NSTIF,IOUT

      REAL(8) :: K(NWK),M(NWM)
	  INTEGER :: MAXA(NNM)
      REAL(8) :: R(NN,NC),EIGV(NC),TT(NN),W(NN),AR(NNC),BR(NNC)
      REAL(8) :: VEC(NC,NC),D(NC),RTOLV(NC),BUP(NC),BLO(NC)
      REAL(8) :: BUPC(NC),RTOL

      DATA K/2.0, 4.0, -1.0, 2.0, -1.0/
      DATA M/0.5, 1.0, 0.5/
      DATA MAXA/1,2,4,6/

      DATA NROOT/2/, NITEM/16/, IFSS/1/, IFPR/1/, NSTIF/16/, IOUT/6/
	  DATA RTOL/1.0E-6/

      CALL SSPACE90(K,M,MAXA,R,EIGV,TT,W,AR,BR,VEC,D,RTOLV,BUP,BLO,BUPC,NN, &
           NNM,NWK,NWM,NROOT,RTOL,NC,NNC,NITEM,IFSS,IFPR,NSTIF,IOUT)
      
      END
 